CREATE TYPE gender as ENUM ('male', 'female');

CREATE TABLE users (
    id SERIAL PRIMARY KEY NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    gender GENDER NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_digest VARCHAR(255) NOT NULL,
);

CREATE TABLE pairs (
    id SERIAL PRIMARY KEY NOT NULL UNIQUE,
    male_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    female_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE datings (
    id SERIAL PRIMARY KEY NOT NULL UNIQUE,
    date DATETIME NOT NULL,
    address VARCHAR(255) NOT NULL,
    pair_id INTEGER REFERENCES pairs(id) ON DELETE CASCADE NOT NULL
);
